# 2026 Flutter Engineering Excellence - Analysis Options
# Enforces strict code quality, architecture patterns, and M3 best practices.

include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # 2026 Strict Enforcement: Treat performance & safety violations as Errors
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    unawaited_futures: error
    avoid_print: error
    missing_required_param: error
    missing_return: error
    must_be_immutable: error

linter:
  rules:
    # --- Performance & Code Robustness ---
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_super_parameters
    - prefer_const_declarations
    - prefer_const_constructors_in_immutables
    
    # --- 2026 AI Collaboration & Readability ---
    - always_declare_return_types # Critical for AI intention understanding
    - require_trailing_commas # Cleaner diffs and formatting
    - prefer_final_locals # Immutability prevents logic bugs
    - annotate_overrides
    - camel_case_types
    - library_names
    
    # --- Async & Concurrency Safety ---
    - unawaited_futures
    - avoid_void_async
    
    # --- Clean Code Hacks ---
    - curly_braces_in_flow_control_structures
    - omit_local_variable_types # Recommended to keep code concise when types are inferred
    - prefer_single_quotes
    - sort_child_properties_last
    - unnecessary_const
    - unnecessary_this
    - use_key_in_widget_constructors
