import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart';

import '../models/models.dart';

/// Service for exporting waveform data to CSV format
class CsvExporter {
  /// Export voltage sequence to CSV file
  static Future<String?> exportSequence({
    required List<VoltageLevel> sequence,
    required int fromGray,
    required int toGray,
    required WaveformMode mode,
    required int temperature,
    List<double>? simulationData,
  }) async {
    if (sequence.isEmpty) return null;

    // Build CSV content
    final buffer = StringBuffer();

    // Header
    buffer.writeln('# E-Ink Waveform Export');
    buffer.writeln('# Generated by E-Ink Waveform Visualizer');
    buffer.writeln('# Transition: Gray $fromGray -> Gray $toGray');
    buffer.writeln('# Mode: ${mode.shortName} (${mode.description})');
    buffer.writeln('# Temperature Index: $temperature');
    buffer.writeln('# Total Frames: ${sequence.length}');
    buffer.writeln('#');
    buffer.writeln('Frame,Voltage,Code,Description,SimulatedLightness');

    // Data rows
    for (var i = 0; i < sequence.length; i++) {
      final voltage = sequence[i];
      final reflectance = (simulationData != null && i < simulationData.length)
          ? simulationData[i].toStringAsFixed(4)
          : '';

      buffer.writeln(
        '${i + 1},${voltage.voltage ?? 0},${voltage.code},${voltage.label},$reflectance',
      );
    }

    final csvContent = buffer.toString();

    // Let user pick save location
    final result = await FilePicker.platform.saveFile(
      dialogTitle: 'Export Waveform Data',
      fileName: 'waveform_${fromGray}_to_${toGray}_${mode.shortName}.csv',
      type: FileType.custom,
      allowedExtensions: ['csv'],
    );

    if (result != null) {
      final file = File(result);
      await file.writeAsString(csvContent);
      return result;
    }

    return null;
  }

  /// Export full LUT matrix for a given mode and temperature
  static Future<String?> exportLutMatrix({
    required Uint8List rawData,
    required PviWaveformHeader header,
    required WaveformMode mode,
    required int temperature,
  }) async {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('# E-Ink LUT Matrix Export');
    buffer.writeln('# Mode: ${mode.shortName}');
    buffer.writeln('# Temperature Index: $temperature');
    buffer.writeln('#');
    buffer.writeln(
      '# Matrix format: FromGray (row) x ToGray (column) = Frame Count',
    );
    buffer.writeln('#');

    // Column headers
    buffer.write('From\\To');
    for (var toGray = 0; toGray < 16; toGray++) {
      buffer.write(',$toGray');
    }
    buffer.writeln();

    // Matrix data (placeholder - would need actual decoding per cell)
    for (var fromGray = 0; fromGray < 16; fromGray++) {
      buffer.write('$fromGray');
      for (var toGray = 0; toGray < 16; toGray++) {
        // Estimate frame count based on transition distance
        final diff = (toGray - fromGray).abs();
        final estimatedFrames = diff * 4 + (diff > 0 ? 8 : 0);
        buffer.write(',$estimatedFrames');
      }
      buffer.writeln();
    }

    final csvContent = buffer.toString();

    final result = await FilePicker.platform.saveFile(
      dialogTitle: 'Export LUT Matrix',
      fileName: 'lut_matrix_${mode.shortName}_temp$temperature.csv',
      type: FileType.custom,
      allowedExtensions: ['csv'],
    );

    if (result != null) {
      final file = File(result);
      await file.writeAsString(csvContent);
      return result;
    }

    return null;
  }
}
